# Generated by Django 5.0.4 on 2024-05-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('conductor', 'Conductor'), ('cliente', 'Cliente'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
