# Generated by Django 5.0.4 on 2024-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(default=1)),
                ('estado', models.CharField(default='Disponible', max_length=10)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('receptor', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
