# Generated by Django 5.0.4 on 2024-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('evento', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
                ('estado', models.CharField(default='Abierto', max_length=10)),
            ],
        ),
    ]
