# Generated by Django 5.0.4 on 2024-07-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfil_tipo'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_seguimiento', models.DateField(auto_now_add=True)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.evento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
