# Generated by Django 5.0.4 on 2024-05-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='En espera', max_length=10),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conductor', models.IntegerField(default=1)),
                ('calificacion', models.IntegerField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='requests.solicitud')),
            ],
        ),
    ]
