# Generated by Django 5.0.4 on 2024-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='seguimiento_creado',
            field=models.BooleanField(default=False),
        ),
    ]
