# Generated by Django 5.0.4 on 2024-05-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_solicitud_estado_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
